Repository exercism/awk, pull requests merged in 2022-06, with the labels that each got.

#30 Run `configlet fmt` on exercises
  exercises/practice/acronym/.meta/config.json
  exercises/practice/armstrong-numbers/.meta/config.json
  exercises/practice/bob/.meta/config.json
  exercises/practice/darts/.meta/config.json
  exercises/practice/grains/.meta/config.json
  exercises/practice/hamming/.meta/config.json
  exercises/practice/hello-world/.meta/config.json
  exercises/practice/leap/.meta/config.json
  exercises/practice/pangram/.meta/config.json
  exercises/practice/raindrops/.meta/config.json
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/two-fer/.meta/config.json
Labels: x:size/small

#32 Pig Latin, take 2
  config.json
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/pig-latin/.meta/config.json
  exercises/practice/pig-latin/.meta/example.awk
  exercises/practice/pig-latin/.meta/tests.toml
  exercises/practice/pig-latin/bats-extra.bash
  exercises/practice/pig-latin/pig-latin.awk
  exercises/practice/pig-latin/test-pig-latin.bats
Labels: x:type/content, x:module/practice-exercise, x:action/create

#41 Update HOWTO-port
  HOWTO-port-an-exercise.md
Labels: x:size/small

#59 list-ops doc: apply review suggestion; reformat
  exercises/practice/list-ops/.docs/instructions.append.md
Labels: x:action/improve, x:rep/tiny

#116 Some exercises with commented-out skips
  bin/validate_one_exercise
  exercises/practice/change/test-change.bats
  exercises/practice/list-ops/test-list-ops.bats
  exercises/practice/rectangles/test-rectangles.bats
  exercises/practice/run-length-encoding/test-run-length-encoding.bats
  exercises/practice/scrabble-score/test-scrabble-score.bats
  exercises/practice/wordy/test-wordy.bats
Labels: x:rep/small

#115 Forego some exercises
  config.json
Labels: x:rep/small

#119 Fix spelling of "paasio" in foregone list
  config.json
Labels: x:rep/tiny

#122 wrong varname in comment
  exercises/practice/armstrong-numbers/.meta/example.awk
  exercises/practice/armstrong-numbers/armstrong-numbers.awk
Labels: x:rep/tiny

#135 fix filename
  exercises/practice/matrix/.docs/instructions.append.md
Labels: x:rep/tiny

#138 list-ops: param typo
  exercises/practice/list-ops/list-ops.awk
Labels: x:rep/tiny
