Repository exercism/awk, pull requests merged in 2023-09, with the labels that each got.

#214 expand the str-to-num examples
  concepts/nums-strs/about.md
  concepts/nums-strs/introduction.md
Labels: x:type/docs, x:rep/tiny

#216 Sync track docs and configs
  exercises/practice/darts/.docs/instructions.md
  exercises/practice/list-ops/.docs/instructions.md
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/secret-handshake/.meta/config.json
Labels: x:action/sync, x:size/small, x:rep/small

#219 Fix broken hint link in Basics concept exercise
  exercises/concept/basics/.docs/hints.md
Labels: x:type/docs, x:rep/tiny

#220 Sync docs and anagram tests
  exercises/practice/acronym/.docs/instructions.md
  exercises/practice/affine-cipher/.docs/instructions.md
  exercises/practice/all-your-base/.docs/instructions.md
  exercises/practice/allergies/.docs/instructions.md
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/test-anagram.bats
  exercises/practice/armstrong-numbers/.docs/instructions.md
  exercises/practice/etl/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/list-ops/.docs/instructions.md
  exercises/practice/pangram/.docs/introduction.md
  exercises/practice/protein-translation/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/introduction.md
  exercises/practice/rotational-cipher/.docs/instructions.md
  exercises/practice/secret-handshake/.docs/instructions.md
  exercises/practice/series/.docs/instructions.md
  exercises/practice/wordy/.docs/instructions.md
Labels: x:action/sync, x:size/small, x:rep/small

#221 Emphasize the need for UTC flag in time functions
  exercises/practice/gigasecond/.docs/instructions.append.md
  exercises/practice/gigasecond/.meta/example.awk
Labels: x:rep/small

#222 Convert backtick (`) admonition fences to tildes (~)
  exercises/practice/etl/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
  exercises/practice/pangram/.docs/introduction.md
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/introduction.md
  exercises/practice/secret-handshake/.docs/instructions.md
Labels: x:size/tiny
